[project]
name="kalawindow"
version="1-7-0"
kmake="project.kmake"

[targets]
dir_kh="../kalaheaders"
fork_spv="../../_forks/spirv-reflect"
ext_kh="external/kalaheaders"
ext_vk="external/vulkan"
ext_spv="external/spirv-reflect"

[windows-copy]
kh_license=[ "${dir_kh}/LICENSE.md", "${ext_kh}/LICENSE.md" ]
kh_readme=[ "${dir_kh}/README.md", "${ext_kh}/README.md" ]
kh_include=[ "${dir_kh}/include", "${ext_kh}/include" ]
vk_win_stuff=[ "${fork_spv}/_vk", "${ext_vk}" ]
vk_spv_stuff=[ "${fork_spv}/_build", "${ext_spv}" ]

[windows-post-build-copy]
kw_bin_rel=[ "build/temp/release-windows/kalawindow.lib", "build/${version}/kalawindow.lib" ]
kw_bin_deb=[ "build/temp/debug-windows/kalawindowd.lib", "build/${version}/kalawindowd.lib" ]
kw_include=[ "include", "build/${version}/include" ]
kw_license=[ "LICENSE.md", "build/${version}/LICENSE.md" ]
kw_readme=[ "README.md", "build/${version}/README.md" ]
kh_stuff=[ "${ext_kh}", "build/${version}/kalaheaders" ]
vk_win_stuff=[ "${ext_vk}", "build/${version}/vulkan" ]
vk_spv_stuff=[ "${ext_spv}", "build/${version}/spirv-reflect" ]

[windows-gnu-copy]
kh_license=[ "${dir_kh}/LICENSE.md", "${ext_kh}/LICENSE.md" ]
kh_readme=[ "${dir_kh}/README.md", "${ext_kh}/README.md" ]
kh_include=[ "${dir_kh}/include", "${ext_kh}/include" ]
vk_win_stuff=[ "${fork_spv}/_vk", "${ext_vk}" ]
vk_spv_stuff=[ "${fork_spv}/_build", "${ext_spv}" ]

[windows-gnu-post-build-copy]
kw_bin_rel=[ "build/temp/release-windows-gnu/kalawindow-gnu.lib", "build/${version}/kalawindow-gnu.lib" ]
kw_bin_deb=[ "build/temp/debug-windows-gnu/kalawindow-gnud.lib", "build/${version}/kalawindow-gnud.lib" ]
kw_include=[ "include", "build/${version}/include" ]
kw_license=[ "LICENSE.md", "build/${version}/LICENSE.md" ]
kw_readme=[ "README.md", "build/${version}/README.md" ]
kh_stuff=[ "${ext_kh}", "build/${version}/kalaheaders" ]
vk_win_stuff=[ "${ext_vk}", "build/${version}/vulkan" ]
vk_spv_stuff=[ "${ext_spv}", "build/${version}/spirv-reflect" ]

[linux-copy]
kh_license=[ "${dir_kh}/LICENSE.md", "${ext_kh}/LICENSE.md" ]
kh_readme=[ "${dir_kh}/README.md", "${ext_kh}/README.md" ]
kh_include=[ "${dir_kh}/include", "${ext_kh}/include" ]
vk_win_stuff=[ "${fork_spv}/_vk", "${ext_vk}" ]
vk_spv_stuff=[ "${fork_spv}/_build", "${ext_spv}" ]

[linux-post-build-copy]
kw_bin_rel=[ "build/temp/release-linux/libkalawindow.a", "build/${version}/libkalawindow.a" ]
kw_bin_deb=[ "build/temp/debug-linux/libkalawindowd.a", "build/${version}/libkalawindowd.a" ]
kw_include=[ "include", "build/${version}/include" ]
kw_license=[ "LICENSE.md", "build/${version}/LICENSE.md" ]
kw_readme=[ "README.md", "build/${version}/README.md" ]
kh_stuff=[ "${ext_kh}", "build/${version}/kalaheaders" ]
vk_win_stuff=[ "${ext_vk}", "build/${version}/vulkan" ]
vk_spv_stuff=[ "${ext_spv}", "build/${version}/spirv-reflect" ]
