//Copyright(C) 2025 Lost Empire Entertainment
//This program comes with ABSOLUTELY NO WARRANTY.
//This is free software, and you are welcome to redistribute it under certain conditions.
//Read LICENSE.md for more information.

#ifdef KALAWINDOW_SUPPORT_VULKAN

#pragma once

#include <unordered_map>

namespace KalaWindow::Graphics
{
	using std::unordered_map;

	enum class VulkanInstanceExtensions
	{
		// Debugging & Tooling

		V_IE_debug_report,
		V_IE_validation_flags,

		// Device & Properties

		V_IE_device_group_creation,
		V_IE_get_physical_device_properties2,

		// External & Synchronization

		V_IE_external_fence_capabilities,
		V_IE_external_memory_capabilities,
		V_IE_external_semaphore_capabilities,

		// Miscellaneous

		V_IE_portability_enumeration,

		// Surface & Windowing

		V_IE_acquire_xlib_display,
		V_IE_surface_maintenance1,
		V_IE_surface_protected_capabilities,
		V_IE_win32_surface,
		V_IE_xcb_surface,
		V_IE_xlib_surface
	};

	static const unordered_map<VulkanInstanceExtensions, const char*> vulkanInstanceExtensionsInfo =
	{
		// Debugging & Tooling

		{ VulkanInstanceExtensions::V_IE_debug_report,     "VK_EXT_debug_report" },
		{ VulkanInstanceExtensions::V_IE_validation_flags, "VK_EXT_validation_flags" },

		// Device & Properties

		{ VulkanInstanceExtensions::V_IE_device_group_creation,           "VK_KHR_device_group_creation" },
		{ VulkanInstanceExtensions::V_IE_get_physical_device_properties2, "VK_KHR_get_physical_device_properties2" },

		// External & Synchronization

		{ VulkanInstanceExtensions::V_IE_external_fence_capabilities,     "VK_KHR_external_fence_capabilities" },
		{ VulkanInstanceExtensions::V_IE_external_memory_capabilities,    "VK_KHR_external_memory_capabilities" },
		{ VulkanInstanceExtensions::V_IE_external_semaphore_capabilities, "VK_KHR_external_semaphore_capabilities" },

		// Miscellaneous

		{ VulkanInstanceExtensions::V_IE_portability_enumeration, "VK_KHR_portability_enumeration" },

		// Surface & Windowing

		{ VulkanInstanceExtensions::V_IE_acquire_xlib_display,           "VK_EXT_acquire_xlib_display" },
		{ VulkanInstanceExtensions::V_IE_surface_maintenance1,           "VK_EXT_surface_maintenance1" },
		{ VulkanInstanceExtensions::V_IE_surface_protected_capabilities, "VK_KHR_surface_protected_capabilities" },
		{ VulkanInstanceExtensions::V_IE_win32_surface,                  "VK_KHR_win32_surface" },
		{ VulkanInstanceExtensions::V_IE_xcb_surface,                    "VK_KHR_xcb_surface" },
		{ VulkanInstanceExtensions::V_IE_xlib_surface,                   "VK_KHR_xlib_surface" }
	};

	enum class VulkanDeviceExtensions
	{
		V_DE_khr_sampler_mirror_clamp_to_edge,
		V_DE_ext_debug_marker,
		V_DE_khr_video_queue,
		V_DE_khr_video_decode_queue,
		V_DE_ext_transform_feedback,
		V_DE_khr_video_encode_h264,
		V_DE_khr_video_encode_h265,
		V_DE_khr_video_decode_h264,
		V_DE_khr_dynamic_rendering,
		V_DE_khr_multiview,
		V_DE_khr_device_group,
		V_DE_khr_shader_draw_parameters,
		V_DE_ext_shader_subgroup_ballot,
		V_DE_ext_shader_subgroup_vote,
		V_DE_ext_pipeline_robustness,
		V_DE_khr_maintenance1,
		V_DE_khr_external_memory,
		V_DE_khr_external_memory_win32,
		V_DE_khr_win32_keyed_mutex,
		V_DE_khr_external_semaphore,
		V_DE_khr_external_semaphore_win32,
		V_DE_khr_push_descriptor,
		V_DE_ext_conditional_rendering,
		V_DE_khr_shader_float16_int8,
		V_DE_khr_16bit_storage,
		V_DE_khr_descriptor_update_template,
		V_DE_khr_imageless_framebuffer,
		V_DE_khr_create_renderpass2,
		V_DE_khr_external_fence,
		V_DE_khr_external_fence_win32,
		V_DE_khr_maintenance2,
		V_DE_khr_variable_pointers,
		V_DE_khr_dedicated_allocation,
		V_DE_ext_sampler_filter_minmax,
		V_DE_khr_storage_buffer_storage_class,
		V_DE_ext_inline_uniform_block,
		V_DE_khr_shader_bfloat16,
		V_DE_khr_relaxed_block_layout,
		V_DE_khr_get_memory_requirements2,
		V_DE_khr_image_format_list,
		V_DE_khr_acceleration_structure,
		V_DE_khr_ray_tracing_pipeline,
		V_DE_khr_ray_query,
		V_DE_khr_sampler_ycbcr_conversion,
		V_DE_khr_bind_memory2,
		V_DE_ext_validation_cache,
		V_DE_ext_descriptor_indexing,
		V_DE_ext_shader_viewport_index_layer,
		V_DE_khr_portability_subset,
		V_DE_khr_maintenance3,
		V_DE_khr_draw_indirect_count,
		V_DE_ext_global_priority,
		V_DE_khr_shader_subgroup_extended_types,
		V_DE_khr_8bit_storage,
		V_DE_khr_shader_atomic_int64,
		V_DE_ext_calibrated_timestamps,
		V_DE_khr_video_decode_h265,
		V_DE_ext_vertex_attribute_divisor,
		V_DE_ext_pipeline_creation_feedback,
		V_DE_khr_driver_properties,
		V_DE_khr_shader_float_controls,
		V_DE_khr_depth_stencil_resolve,
		V_DE_khr_timeline_semaphore,
		V_DE_khr_vulkan_memory_model,
		V_DE_ext_fragment_density_map,
		V_DE_ext_scalar_block_layout,
		V_DE_khr_dynamic_rendering_local_read,
		V_DE_khr_shader_quad_control,
		V_DE_khr_spirv_1_4,
		V_DE_ext_memory_priority,
		V_DE_khr_separate_depth_stencil_layouts,
		V_DE_ext_buffer_device_address,
		V_DE_ext_tooling_info,
		V_DE_ext_separate_stencil_usage,
		V_DE_khr_present_wait,
		V_DE_khr_uniform_buffer_standard_layout,
		V_DE_ext_provoking_vertex,
		V_DE_ext_full_screen_exclusive,
		V_DE_khr_buffer_device_address,
		V_DE_ext_host_query_reset,
		V_DE_khr_deferred_host_operations,
		V_DE_khr_pipeline_executable_properties,
		V_DE_ext_host_image_copy,
		V_DE_khr_map_memory2,
		V_DE_ext_map_memory_placed,
		V_DE_ext_shader_atomic_float2,
		V_DE_ext_swapchain_maintenance1,
		V_DE_khr_shader_integer_dot_product,
		V_DE_ext_depth_bias_control,
		V_DE_ext_device_memory_report,
		V_DE_khr_pipeline_library,
		V_DE_khr_shader_non_semantic_info,
		V_DE_khr_present_id,
		V_DE_ext_private_data,
		V_DE_ext_pipeline_creation_cache_control,
		V_DE_khr_video_encode_queue,
		V_DE_ext_descriptor_buffer,
		V_DE_ext_graphics_pipeline_library,
		V_DE_khr_fragment_shader_barycentric,
		V_DE_khr_shader_subgroup_uniform_control_flow,
		V_DE_khr_zero_initialize_workgroup_memory,
		V_DE_ext_mesh_shader,
		V_DE_ext_fragment_density_map2,
		V_DE_khr_workgroup_memory_explicit_layout,
		V_DE_ext_image_compression_control,
		V_DE_ext_attachment_feedback_loop_layout,
		V_DE_ext_device_fault,
		V_DE_ext_rgba10x6_formats,
		V_DE_ext_device_address_binding_report,
		V_DE_ext_depth_clip_control,
		V_DE_ext_primitive_topology_list_restart,
		V_DE_khr_format_feature_flags2,
		V_DE_ext_present_mode_fifo_latest_ready,
		V_DE_ext_pipeline_properties,
		V_DE_ext_frame_boundary,
		V_DE_ext_multisampled_render_to_single_sampled,
		V_DE_ext_primitives_generated_query,
		V_DE_khr_ray_tracing_maintenance1,
		V_DE_ext_global_priority_query,
		V_DE_ext_image_view_min_lod,
		V_DE_ext_multi_draw,
		V_DE_ext_image_2d_view_of_3d,
		V_DE_ext_shader_tile_image,
		V_DE_ext_opacity_micromap,
		V_DE_ext_load_store_op_none,
		V_DE_ext_border_color_swizzle,
		V_DE_ext_pageable_device_local_memory,
		V_DE_khr_maintenance4,
		V_DE_khr_shader_subgroup_rotate,
		V_DE_ext_image_sliced_view_of_3d,
		V_DE_ext_depth_clamp_zero_one,
		V_DE_ext_non_seamless_cube_map,
		V_DE_khr_shader_maximal_reconvergence,
		V_DE_ext_image_compression_control_swapchain,
		V_DE_ext_nested_command_buffer,
		V_DE_ext_external_memory_acquire_unmodified,
		V_DE_ext_extended_dynamic_state3,
		V_DE_ext_subpass_merge_feedback,
		V_DE_ext_shader_module_identifier,
		V_DE_ext_rasterization_order_attachment_access,
		V_DE_ext_legacy_dithering,
		V_DE_ext_pipeline_protected_access,
		V_DE_khr_maintenance5,
		V_DE_khr_present_id2,
		V_DE_khr_present_wait2,
		V_DE_khr_ray_tracing_position_fetch,
		V_DE_ext_shader_object,
		V_DE_khr_pipeline_binary,
		V_DE_ext_mutable_descriptor_type,
		V_DE_ext_legacy_vertex_attributes,
		V_DE_ext_pipeline_library_group_handles,
		V_DE_ext_dynamic_rendering_unused_attachments,
		V_DE_khr_cooperative_matrix,
		V_DE_khr_compute_shader_derivatives,
		V_DE_khr_video_decode_av1,
		V_DE_khr_video_encode_av1,
		V_DE_khr_video_decode_vp9,
		V_DE_khr_video_maintenance1,
		V_DE_ext_attachment_feedback_loop_dynamic_state,
		V_DE_khr_load_store_op_none,
		V_DE_khr_unified_image_layouts,
		V_DE_khr_shader_float_controls2,
		V_DE_khr_shader_expect_assume,
		V_DE_khr_maintenance6,
		V_DE_khr_video_encode_quantization_map,
		V_DE_khr_shader_relaxed_extended_instruction,
		V_DE_khr_maintenance7,
		V_DE_ext_shader_replicated_composites,
		V_DE_ext_shader_float8,
		V_DE_ext_device_generated_commands,
		V_DE_khr_maintenance8,
		V_DE_ext_depth_clamp_control,
		V_DE_khr_maintenance9,
		V_DE_khr_video_maintenance2,
		V_DE_khr_depth_clamp_zero_one,
		V_DE_ext_vertex_attribute_robustness,
		V_DE_khr_robustness2,
		V_DE_ext_fragment_density_map_offset,
		V_DE_ext_zero_initialize_device_memory
	};

	static const unordered_map<VulkanDeviceExtensions, const char*> vulkanDeviceExtensionsInfo = 
	{
		{ VulkanDeviceExtensions::V_DE_khr_sampler_mirror_clamp_to_edge, "" },
		{ VulkanDeviceExtensions::V_DE_ext_debug_marker, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_queue, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_decode_queue, "" },
		{ VulkanDeviceExtensions::V_DE_ext_transform_feedback, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_encode_h264, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_encode_h265, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_decode_h264, "" },
		{ VulkanDeviceExtensions::V_DE_khr_dynamic_rendering, "" },
		{ VulkanDeviceExtensions::V_DE_khr_multiview, "" },
		{ VulkanDeviceExtensions::V_DE_khr_device_group, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_draw_parameters, "" },
		{ VulkanDeviceExtensions::V_DE_ext_shader_subgroup_ballot, "" },
		{ VulkanDeviceExtensions::V_DE_ext_shader_subgroup_vote, "" },
		{ VulkanDeviceExtensions::V_DE_ext_pipeline_robustness, "" },
		{ VulkanDeviceExtensions::V_DE_khr_maintenance1, "" },
		{ VulkanDeviceExtensions::V_DE_khr_external_memory, "" },
		{ VulkanDeviceExtensions::V_DE_khr_external_memory_win32, "" },
		{ VulkanDeviceExtensions::V_DE_khr_win32_keyed_mutex, "" },
		{ VulkanDeviceExtensions::V_DE_khr_external_semaphore, "" },
		{ VulkanDeviceExtensions::V_DE_khr_external_semaphore_win32, "" },
		{ VulkanDeviceExtensions::V_DE_khr_push_descriptor, "" },
		{ VulkanDeviceExtensions::V_DE_ext_conditional_rendering, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_float16_int8, "" },
		{ VulkanDeviceExtensions::V_DE_khr_16bit_storage, "" },
		{ VulkanDeviceExtensions::V_DE_khr_descriptor_update_template, "" },
		{ VulkanDeviceExtensions::V_DE_khr_imageless_framebuffer, "" },
		{ VulkanDeviceExtensions::V_DE_khr_create_renderpass2, "" },
		{ VulkanDeviceExtensions::V_DE_khr_external_fence, "" },
		{ VulkanDeviceExtensions::V_DE_khr_external_fence_win32, "" },
		{ VulkanDeviceExtensions::V_DE_khr_maintenance2, "" },
		{ VulkanDeviceExtensions::V_DE_khr_variable_pointers, "" },
		{ VulkanDeviceExtensions::V_DE_khr_dedicated_allocation, "" },
		{ VulkanDeviceExtensions::V_DE_ext_sampler_filter_minmax, "" },
		{ VulkanDeviceExtensions::V_DE_khr_storage_buffer_storage_class, "" },
		{ VulkanDeviceExtensions::V_DE_ext_inline_uniform_block, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_bfloat16, "" },
		{ VulkanDeviceExtensions::V_DE_khr_relaxed_block_layout, "" },
		{ VulkanDeviceExtensions::V_DE_khr_get_memory_requirements2, "" },
		{ VulkanDeviceExtensions::V_DE_khr_image_format_list, "" },
		{ VulkanDeviceExtensions::V_DE_khr_acceleration_structure, "" },
		{ VulkanDeviceExtensions::V_DE_khr_ray_tracing_pipeline, "" },
		{ VulkanDeviceExtensions::V_DE_khr_ray_query, "" },
		{ VulkanDeviceExtensions::V_DE_khr_sampler_ycbcr_conversion, "" },
		{ VulkanDeviceExtensions::V_DE_khr_bind_memory2, "" },
		{ VulkanDeviceExtensions::V_DE_ext_validation_cache, "" },
		{ VulkanDeviceExtensions::V_DE_ext_descriptor_indexing, "" },
		{ VulkanDeviceExtensions::V_DE_ext_shader_viewport_index_layer, "" },
		{ VulkanDeviceExtensions::V_DE_khr_portability_subset, "" },
		{ VulkanDeviceExtensions::V_DE_khr_maintenance3, "" },
		{ VulkanDeviceExtensions::V_DE_khr_draw_indirect_count, "" },
		{ VulkanDeviceExtensions::V_DE_ext_global_priority, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_subgroup_extended_types, "" },
		{ VulkanDeviceExtensions::V_DE_khr_8bit_storage, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_atomic_int64, "" },
		{ VulkanDeviceExtensions::V_DE_ext_calibrated_timestamps, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_decode_h265, "" },
		{ VulkanDeviceExtensions::V_DE_ext_vertex_attribute_divisor, "" },
		{ VulkanDeviceExtensions::V_DE_ext_pipeline_creation_feedback, "" },
		{ VulkanDeviceExtensions::V_DE_khr_driver_properties, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_float_controls, "" },
		{ VulkanDeviceExtensions::V_DE_khr_depth_stencil_resolve, "" },
		{ VulkanDeviceExtensions::V_DE_khr_timeline_semaphore, "" },
		{ VulkanDeviceExtensions::V_DE_khr_vulkan_memory_model, "" },
		{ VulkanDeviceExtensions::V_DE_ext_fragment_density_map, "" },
		{ VulkanDeviceExtensions::V_DE_ext_scalar_block_layout, "" },
		{ VulkanDeviceExtensions::V_DE_khr_dynamic_rendering_local_read, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_quad_control, "" },
		{ VulkanDeviceExtensions::V_DE_khr_spirv_1_4, "" },
		{ VulkanDeviceExtensions::V_DE_ext_memory_priority, "" },
		{ VulkanDeviceExtensions::V_DE_khr_separate_depth_stencil_layouts, "" },
		{ VulkanDeviceExtensions::V_DE_ext_buffer_device_address, "" },
		{ VulkanDeviceExtensions::V_DE_ext_tooling_info, "" },
		{ VulkanDeviceExtensions::V_DE_ext_separate_stencil_usage, "" },
		{ VulkanDeviceExtensions::V_DE_khr_present_wait, "" },
		{ VulkanDeviceExtensions::V_DE_khr_uniform_buffer_standard_layout, "" },
		{ VulkanDeviceExtensions::V_DE_ext_provoking_vertex, "" },
		{ VulkanDeviceExtensions::V_DE_ext_full_screen_exclusive, "" },
		{ VulkanDeviceExtensions::V_DE_khr_buffer_device_address, "" },
		{ VulkanDeviceExtensions::V_DE_ext_host_query_reset, "" },
		{ VulkanDeviceExtensions::V_DE_khr_deferred_host_operations, "" },
		{ VulkanDeviceExtensions::V_DE_khr_pipeline_executable_properties, "" },
		{ VulkanDeviceExtensions::V_DE_ext_host_image_copy, "" },
		{ VulkanDeviceExtensions::V_DE_khr_map_memory2, "" },
		{ VulkanDeviceExtensions::V_DE_ext_map_memory_placed, "" },
		{ VulkanDeviceExtensions::V_DE_ext_shader_atomic_float2, "" },
		{ VulkanDeviceExtensions::V_DE_ext_swapchain_maintenance1, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_integer_dot_product, "" },
		{ VulkanDeviceExtensions::V_DE_ext_depth_bias_control, "" },
		{ VulkanDeviceExtensions::V_DE_ext_device_memory_report, "" },
		{ VulkanDeviceExtensions::V_DE_khr_pipeline_library, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_non_semantic_info, "" },
		{ VulkanDeviceExtensions::V_DE_khr_present_id, "" },
		{ VulkanDeviceExtensions::V_DE_ext_private_data, "" },
		{ VulkanDeviceExtensions::V_DE_ext_pipeline_creation_cache_control, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_encode_queue, "" },
		{ VulkanDeviceExtensions::V_DE_ext_descriptor_buffer, "" },
		{ VulkanDeviceExtensions::V_DE_ext_graphics_pipeline_library, "" },
		{ VulkanDeviceExtensions::V_DE_khr_fragment_shader_barycentric, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_subgroup_uniform_control_flow, "" },
		{ VulkanDeviceExtensions::V_DE_khr_zero_initialize_workgroup_memory, "" },
		{ VulkanDeviceExtensions::V_DE_ext_mesh_shader, "" },
		{ VulkanDeviceExtensions::V_DE_ext_fragment_density_map2, "" },
		{ VulkanDeviceExtensions::V_DE_khr_workgroup_memory_explicit_layout, "" },
		{ VulkanDeviceExtensions::V_DE_ext_image_compression_control, "" },
		{ VulkanDeviceExtensions::V_DE_ext_attachment_feedback_loop_layout, "" },
		{ VulkanDeviceExtensions::V_DE_ext_device_fault, "" },
		{ VulkanDeviceExtensions::V_DE_ext_rgba10x6_formats, "" },
		{ VulkanDeviceExtensions::V_DE_ext_device_address_binding_report, "" },
		{ VulkanDeviceExtensions::V_DE_ext_depth_clip_control, "" },
		{ VulkanDeviceExtensions::V_DE_ext_primitive_topology_list_restart, "" },
		{ VulkanDeviceExtensions::V_DE_khr_format_feature_flags2, "" },
		{ VulkanDeviceExtensions::V_DE_ext_present_mode_fifo_latest_ready, "" },
		{ VulkanDeviceExtensions::V_DE_ext_pipeline_properties, "" },
		{ VulkanDeviceExtensions::V_DE_ext_frame_boundary, "" },
		{ VulkanDeviceExtensions::V_DE_ext_multisampled_render_to_single_sampled, "" },
		{ VulkanDeviceExtensions::V_DE_ext_primitives_generated_query, "" },
		{ VulkanDeviceExtensions::V_DE_khr_ray_tracing_maintenance1, "" },
		{ VulkanDeviceExtensions::V_DE_ext_global_priority_query, "" },
		{ VulkanDeviceExtensions::V_DE_ext_image_view_min_lod, "" },
		{ VulkanDeviceExtensions::V_DE_ext_multi_draw, "" },
		{ VulkanDeviceExtensions::V_DE_ext_image_2d_view_of_3d, "" },
		{ VulkanDeviceExtensions::V_DE_ext_shader_tile_image, "" },
		{ VulkanDeviceExtensions::V_DE_ext_opacity_micromap, "" },
		{ VulkanDeviceExtensions::V_DE_ext_load_store_op_none, "" },
		{ VulkanDeviceExtensions::V_DE_ext_border_color_swizzle, "" },
		{ VulkanDeviceExtensions::V_DE_ext_pageable_device_local_memory, "" },
		{ VulkanDeviceExtensions::V_DE_khr_maintenance4, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_subgroup_rotate, "" },
		{ VulkanDeviceExtensions::V_DE_ext_image_sliced_view_of_3d, "" },
		{ VulkanDeviceExtensions::V_DE_ext_depth_clamp_zero_one, "" },
		{ VulkanDeviceExtensions::V_DE_ext_non_seamless_cube_map, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_maximal_reconvergence, "" },
		{ VulkanDeviceExtensions::V_DE_ext_image_compression_control_swapchain, "" },
		{ VulkanDeviceExtensions::V_DE_ext_nested_command_buffer, "" },
		{ VulkanDeviceExtensions::V_DE_ext_external_memory_acquire_unmodified, "" },
		{ VulkanDeviceExtensions::V_DE_ext_extended_dynamic_state3, "" },
		{ VulkanDeviceExtensions::V_DE_ext_subpass_merge_feedback, "" },
		{ VulkanDeviceExtensions::V_DE_ext_shader_module_identifier, "" },
		{ VulkanDeviceExtensions::V_DE_ext_rasterization_order_attachment_access, "" },
		{ VulkanDeviceExtensions::V_DE_ext_legacy_dithering, "" },
		{ VulkanDeviceExtensions::V_DE_ext_pipeline_protected_access, "" },
		{ VulkanDeviceExtensions::V_DE_khr_maintenance5, "" },
		{ VulkanDeviceExtensions::V_DE_khr_present_id2, "" },
		{ VulkanDeviceExtensions::V_DE_khr_present_wait2, "" },
		{ VulkanDeviceExtensions::V_DE_khr_ray_tracing_position_fetch, "" },
		{ VulkanDeviceExtensions::V_DE_ext_shader_object, "" },
		{ VulkanDeviceExtensions::V_DE_khr_pipeline_binary, "" },
		{ VulkanDeviceExtensions::V_DE_ext_mutable_descriptor_type, "" },
		{ VulkanDeviceExtensions::V_DE_ext_legacy_vertex_attributes, "" },
		{ VulkanDeviceExtensions::V_DE_ext_pipeline_library_group_handles, "" },
		{ VulkanDeviceExtensions::V_DE_ext_dynamic_rendering_unused_attachments, "" },
		{ VulkanDeviceExtensions::V_DE_khr_cooperative_matrix, "" },
		{ VulkanDeviceExtensions::V_DE_khr_compute_shader_derivatives, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_decode_av1, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_encode_av1, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_decode_vp9, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_maintenance1, "" },
		{ VulkanDeviceExtensions::V_DE_ext_attachment_feedback_loop_dynamic_state, "" },
		{ VulkanDeviceExtensions::V_DE_khr_load_store_op_none, "" },
		{ VulkanDeviceExtensions::V_DE_khr_unified_image_layouts, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_float_controls2, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_expect_assume, "" },
		{ VulkanDeviceExtensions::V_DE_khr_maintenance6, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_encode_quantization_map, "" },
		{ VulkanDeviceExtensions::V_DE_khr_shader_relaxed_extended_instruction, "" },
		{ VulkanDeviceExtensions::V_DE_khr_maintenance7, "" },
		{ VulkanDeviceExtensions::V_DE_ext_shader_replicated_composites, "" },
		{ VulkanDeviceExtensions::V_DE_ext_shader_float8, "" },
		{ VulkanDeviceExtensions::V_DE_ext_device_generated_commands, "" },
		{ VulkanDeviceExtensions::V_DE_khr_maintenance8, "" },
		{ VulkanDeviceExtensions::V_DE_ext_depth_clamp_control, "" },
		{ VulkanDeviceExtensions::V_DE_khr_maintenance9, "" },
		{ VulkanDeviceExtensions::V_DE_khr_video_maintenance2, "" },
		{ VulkanDeviceExtensions::V_DE_khr_depth_clamp_zero_one, "" },
		{ VulkanDeviceExtensions::V_DE_ext_vertex_attribute_robustness, "" },
		{ VulkanDeviceExtensions::V_DE_khr_robustness2, "" },
		{ VulkanDeviceExtensions::V_DE_ext_fragment_density_map_offset, "" },
		{ VulkanDeviceExtensions::V_DE_ext_zero_initialize_device_memory, "" }
	};
}

#endif //KALAWINDOW_SUPPORT_VULKAN